# Generated by Django 4.2 on 2023-05-30 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0004_resetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 7, 40, 18, 170234, tzinfo=datetime.timezone.utc), max_length=150, unique=True),
        ),
    ]
