# Generated by Django 4.2 on 2023-05-30 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0005_resetpasswordtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 8, 8, 58, 592150, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
