# Generated by Django 4.2 on 2023-06-02 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0007_alter_resetpasswordtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 20, 25, 32, 196245, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
