# Generated by Django 4.2 on 2023-06-07 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0008_alter_resetpasswordtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 5, 58, 24, 74429, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
