# Generated by Django 4.2 on 2023-06-07 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0009_alter_resetpasswordtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 5, 59, 3, 855617, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
