# Generated by Django 4.2 on 2023-07-05 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0012_alter_resetpasswordtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 6, 16, 48, 763960, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
