# Generated by Django 4.2 on 2023-07-05 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0013_alter_resetpasswordtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 10, 56, 26, 950868, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
