# Generated by Django 4.2 on 2023-07-05 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0014_alter_resetpasswordtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 19, 1, 18, 707023, tzinfo=datetime.timezone.utc), max_length=150),
        ),
    ]
