# Generated by Django 4.2 on 2023-06-02 20:25

import category.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Product Name')),
                ('description', models.CharField(max_length=150, verbose_name='Product Description')),
                ('Price', models.IntegerField(verbose_name='Price of Product')),
                ('Quantity', models.IntegerField(verbose_name='Quantity of Product')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=category.models.product_photo_upload, verbose_name='Product Image')),
                ('imageURL', models.URLField(blank=True, null=True, verbose_name='Image url')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category of Product')),
            ],
        ),
    ]
