# Generated by Django 4.2 on 2023-07-05 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 10, 56, 26, 956869, tzinfo=datetime.timezone.utc), verbose_name='Estimated Arrival Date'),
        ),
    ]
