# Generated by Django 4.2 on 2023-07-05 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 19, 1, 18, 713842, tzinfo=datetime.timezone.utc), verbose_name='Estimated Arrival Date'),
        ),
    ]
