# Generated by Django 4.2 on 2023-07-10 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 14, 7, 24, 712780, tzinfo=datetime.timezone.utc), verbose_name='Estimated Arrival Date'),
        ),
    ]
